name: 'SeedGPT Create Patch'
description: 'Creates and uploads failure recovery patch on workflow failure'

inputs:
  prefix:
    description: 'Patch file prefix (e.g., seedpy-resolver)'
    required: true
  run_id:
    description: 'GitHub run ID'
    required: true
  run_attempt:
    description: 'GitHub run attempt number'
    required: true

runs:
  using: composite
  steps:
    - name: Create resolver patch
      shell: bash
      run: |
        set -euo pipefail

        PATCH_NAME="${{ inputs.prefix }}-${{ inputs.run_id }}-${{ inputs.run_attempt }}.patch"

        git status --porcelain=v1 || true
        git log -n 50 --oneline --decorate || true

        # Prefer preserving commits if any were created during the run.
        # GITHUB_SHA points at the checked-out commit from the workflow trigger.
        # If no commits exist, fall back to a plain diff so work is still recoverable.
        git format-patch --stdout "${GITHUB_SHA}..HEAD" > "${PATCH_NAME}" || true
        if [ ! -s "${PATCH_NAME}" ]; then
          echo "No commits found in ${GITHUB_SHA}..HEAD; falling back to git diff"
          git diff > "${PATCH_NAME}" || true
        fi

        ls -lah "${PATCH_NAME}" || true
        echo "PATCH_NAME=${PATCH_NAME}" >> $GITHUB_ENV

    - name: Upload resolver patch artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.prefix }}-patch-${{ inputs.run_id }}-${{ inputs.run_attempt }}
        path: ${{ env.PATCH_NAME }}
        if-no-files-found: error
